version: '3'
services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres_password
      - ENV=/root/.shinit
    volumes:
      - ./api:/var/www/html
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
    depends_on:
      - api
      - client
    restart: always
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
