apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config-map
data:

  ##### START FASTCGI INGRESS CONFIG #####
  SCRIPT_FILENAME: '/var/www/html/public/index.php'
  ##### END FASTCGI INGRESS CONFIG #####
