kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config-map
data:
  SCRIPT_FILENAME: '/var/www/html/public/index.php'
  default.conf: |
        server {
            listen 80 default_server;
            listen [::]:80 default_server;
 
            root /var/www/html/public;

            location / {
                try_files $uri $uri/ /index.php;
            }

            location ~ \.php$ {
                fastcgi_pass 127.0.0.1:9000;
                include fastcgi_params;
                fastcgi_index /index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param SCRIPT_NAME $fastcgi_script_name;
            }
        }
